In [2]:
import math
import torch
from kaolin.render.camera import Camera, CameraExtrinsics, PinholeIntrinsics, OrthographicIntrinsics

In [ ]:
# Build the camera extrinsics object from lookat
world2cam = torch.tensor([[1.0, 0.0, 0.0, 0.5],
                          [0.0, 1.0, 0.0, 0.5],
                          [0.0, 0.0, 1.0, 0.5],
                          [0.0, 0.0, 0.0, 1.0]], device='cuda')  # 3x3 orientation within the world
extrinsics = CameraExtrinsics.from_view_matrix(view_matrix=world2cam)
# Use pinhole camera intrinsics, construct using field-of-view (other useful args: camera_fov_direction, x0, y0)
intrinsics = PinholeIntrinsics.from_fov(width=800, height=600, fov=math.radians(45.0), device='cuda')
camera = Camera(extrinsics=extrinsics, intrinsics=intrinsics)

print('--- Camera ---')
print(camera)

--- Camera 2 ---
CameraExtrinsics of 1 cameras, of coordinate system: 
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]], device='cuda:0'). 
Camera #0 View Matrix: 
tensor([[[1.0000, 0.0000, 0.0000, 0.5000],
         [0.0000, 1.0000, 0.0000, 0.5000],
         [0.0000, 0.0000, 1.0000, 0.5000],
         [0.0000, 0.0000, 0.0000, 1.0000]]], device='cuda:0'),
Camera #0 Inverse View Matrix: 
tensor([[[ 1.0000,  0.0000,  0.0000, -0.5000],
         [ 0.0000,  1.0000,  0.0000, -0.5000],
         [ 0.0000,  0.0000,  1.0000, -0.5000],
         [ 0.0000,  0.0000,  0.0000,  1.0000]]], device='cuda:0')

PinholeIntrinsics of 1 cameras of resolution 800x600.
Camera #0: {'x0': 0.0, 'y0': 0.0, 'focal_x': 724.2640991210938, 'focal_y': 724.2640991210938}

